runners:
  - name: vllm-gpu-runner
    cloud: vast_ai
    instance_type: 1xRTX_4090
    machine_image: nvidia/cuda:12.4.1-devel-ubuntu22.04
    labels:
      - cirun-vllm-gpu
    extra_config:
      disk_space: 100
      min_ram: 16
